# followed example from https://www.r-bloggers.com/2019/02/developing-r-packages-with-usethis-and-gitlab-ci-part-iii/
image: openanalytics/r-base:latest 

cache:
  key: global-cache
  paths:
      - ci/lib/


test:  
  script:
    - apt-get update && apt-get install --no-install-recommends -y libxml2-dev
    - echo "options(crayon.enabled=TRUE)" > .Rprofile   # force crayon  mode
    - echo "Installing dependencies"
    - R -e 'install.packages(c("roxygen2","tinytest", "tinytest2JUnit"), repos = c(OA = "https://repos.openanalytics.eu/repo/public/", CRAN = "https://cloud.r-project.org"))'
    - PKG="$(R CMD build . | grep -Eo '[[:alnum:]\._]+\.tar\.gz')"
    - R CMD check ${PKG} --no-manual --no-build-vignettes



