# Generated by packamon: do not edit by hand
# Instead of modifying this file, you can modify a template. See ?init for details.

FROM registry.openanalytics.eu/openanalytics/r-ver:4.4.0

# System libraries (incl. system requirements for R packages)
RUN apt-get update && apt-get install --no-install-recommends -y \
    libcurl4-openssl-dev \
    libicu-dev \
    libssl-dev \
    libxml2-dev \
    make \
    pandoc \
    && rm -rf /var/lib/apt/lists/*

RUN echo \
    'options(repos = c(CRAN = gsub("/([0-9-]*)$", "/latest", Sys.getenv("CRAN", "https://cloud.r-project.org")), CRAN.source = "https://cloud.r-project.org"))' \
    >> $(R RHOME)/etc/Rprofile.site

# install dependencies
RUN R -q -e "options(warn = 2); \
    install.packages('remotes'); \
    remotes::install_version('brew', version = '1.0-10', upgrade = FALSE); \
    remotes::install_version('cli', version = '3.6.2', upgrade = FALSE); \
    remotes::install_version('commonmark', version = '1.9.1', upgrade = FALSE); \
    remotes::install_version('cpp11', version = '0.4.7', upgrade = FALSE); \
    remotes::install_version('crayon', version = '1.5.2', upgrade = FALSE); \
    remotes::install_version('curl', version = '5.2.1', upgrade = FALSE); \
    remotes::install_version('digest', version = '0.6.35', upgrade = FALSE); \
    remotes::install_version('evaluate', version = '0.23', upgrade = FALSE); \
    remotes::install_version('fs', version = '1.6.4', upgrade = FALSE)"
RUN R -q -e "options(warn = 2); \
    remotes::install_version('glue', version = '1.7.0', upgrade = FALSE); \
    remotes::install_version('jsonlite', version = '1.8.8', upgrade = FALSE); \
    remotes::install_version('lazyeval', version = '0.2.2', upgrade = FALSE); \
    remotes::install_version('magrittr', version = '2.0.3', upgrade = FALSE); \
    remotes::install_version('mime', version = '0.12', upgrade = FALSE); \
    remotes::install_version('ps', version = '1.7.6', upgrade = FALSE); \
    remotes::install_version('R6', version = '2.5.1', upgrade = FALSE); \
    remotes::install_version('rlang', version = '1.1.3', upgrade = FALSE); \
    remotes::install_version('rprojroot', version = '2.0.4', upgrade = FALSE); \
    remotes::install_version('stringi', version = '1.8.4', upgrade = FALSE)"
RUN R -q -e "options(warn = 2); \
    remotes::install_version('sys', version = '3.4.2', upgrade = FALSE); \
    remotes::install_version('tinytest', version = '1.4.1', upgrade = FALSE); \
    remotes::install_version('withr', version = '3.0.0', upgrade = FALSE); \
    remotes::install_version('xfun', version = '0.44', upgrade = FALSE); \
    remotes::install_version('yaml', version = '2.3.8', upgrade = FALSE); \
    remotes::install_version('askpass', version = '1.2.0', upgrade = FALSE); \
    remotes::install_version('desc', version = '1.4.3', upgrade = FALSE); \
    remotes::install_version('highr', version = '0.11', upgrade = FALSE); \
    remotes::install_version('lifecycle', version = '1.0.4', upgrade = FALSE); \
    remotes::install_version('processx', version = '3.8.4', upgrade = FALSE)"
RUN R -q -e "options(warn = 2); \
    remotes::install_version('rex', version = '1.2.1', upgrade = FALSE); \
    remotes::install_version('xml2', version = '1.3.6', upgrade = FALSE); \
    remotes::install_version('callr', version = '3.7.6', upgrade = FALSE); \
    remotes::install_version('knitr', version = '1.47', upgrade = FALSE); \
    remotes::install_version('openssl', version = '2.2.0', upgrade = FALSE); \
    remotes::install_version('vctrs', version = '0.6.5', upgrade = FALSE); \
    remotes::install_version('httr', version = '1.4.7', upgrade = FALSE); \
    remotes::install_version('pkgbuild', version = '1.4.4', upgrade = FALSE); \
    remotes::install_version('purrr', version = '1.0.2', upgrade = FALSE); \
    remotes::install_version('stringr', version = '1.5.1', upgrade = FALSE)"
RUN R -q -e "options(warn = 2); \
    remotes::install_version('covr', version = '3.6.4', upgrade = FALSE); \
    remotes::install_version('pkgload', version = '1.3.4', upgrade = FALSE); \
    remotes::install_version('roxygen2', version = '7.3.1', upgrade = FALSE)"

