# Generated by packamon: do not edit by hand
# Instead of modifying this file, you can modify a template. See ?init for details.

FROM openanalytics/r-ver:4.1.2

# System libraries (incl. system requirements for R packages)
RUN apt-get update && apt-get install --no-install-recommends -y \
    libssl-dev \
    pandoc \
    make \
    libxml2-dev \
    libicu-dev \
    libcurl4-openssl-dev \
    && rm -rf /var/lib/apt/lists/*

RUN R -e "cat(\"local(options(repos = structure(NA_character_, .Names = NA_character_)))\n\", file = R.home('etc/Rprofile.site'), append = TRUE)"

# install dependencies
RUN R -q -e "install.packages('remotes')" && \
    R -q -e "install.packages('brew')" && \
    R -q -e "install.packages('cli')" && \
    R -q -e "install.packages('commonmark')" && \
    R -q -e "install.packages('cpp11')" && \
    R -q -e "install.packages('crayon')" && \
    R -q -e "install.packages('curl')" && \
    R -q -e "install.packages('digest')" && \
    R -q -e "install.packages('evaluate')" && \
    R -q -e "install.packages('fs')"
RUN R -q -e "install.packages('glue')" && \
    R -q -e "install.packages('jsonlite')" && \
    R -q -e "install.packages('lazyeval')" && \
    R -q -e "install.packages('magrittr')" && \
    R -q -e "install.packages('mime')" && \
    R -q -e "install.packages('R6')" && \
    R -q -e "install.packages('rlang')" && \
    R -q -e "install.packages('rprojroot')" && \
    R -q -e "install.packages('stringi')" && \
    R -q -e "install.packages('sys')"
RUN R -q -e "install.packages('tinytest')" && \
    R -q -e "install.packages('withr')" && \
    R -q -e "install.packages('xfun')" && \
    R -q -e "install.packages('xml2')" && \
    R -q -e "install.packages('yaml')" && \
    R -q -e "install.packages('askpass')" && \
    R -q -e "install.packages('desc')" && \
    R -q -e "install.packages('highr')" && \
    R -q -e "install.packages('lifecycle')" && \
    R -q -e "install.packages('rex')"
RUN R -q -e "install.packages('knitr')" && \
    R -q -e "install.packages('openssl')" && \
    R -q -e "install.packages('pkgload')" && \
    R -q -e "install.packages('vctrs')" && \
    R -q -e "install.packages('httr')" && \
    R -q -e "install.packages('purrr')" && \
    R -q -e "install.packages('stringr')" && \
    R -q -e "install.packages('covr')" && \
    R -q -e "install.packages('roxygen2')"


