
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: build-docker

jobs:
  checkout:
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Build an image
        env:
          GIT_CLONE_TOKEN: ${{ secrets.GH_PAT }}
          REPOSITORY_NAME: "tinytest2JUnit"
        run: |
          docker build -t 'tinytest2junit' . 
          docker run --workdir /workspace -v "$PWD:/workspace" -it -d --name app ubuntu cat -
          docker exec -it app R -q -e 'roxygen2::roxygenize("tinytest2JUnit")'   # command will be executed in the container in the /workspace directory (containing your repository)
          docker exec -it app R CMD build tinytest2JUnit  
          docker cp app:/workspace/my_ouptput.txt .

